name: Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Protostar
        run: curl -L https://raw.githubusercontent.com/software-mansion/protostar/master/install.sh | bash
      - name: Run Tests
        run: protostar test
  